customCommands:
  - key: 'x'
    context: 'files'
    command: "rm {{.SelectedFile.Name | quote}}"
    prompts: 
    - type: 'confirm'
      title: "Delete file"
      body: 'Are you sure you want to delete {{.SelectedFile.Name | quote}}?'

git:
  commit:
    signOff: true
#   paging:
#     colorArg: always
#     pager: delta --dark --paging=never
#     # externalDiffCommand: git diff --color=always
keybinding:
  universal:
    prevBlock-alt: ""
    nextBlock-alt: ""
  files:
    commitChanges: C
    commitChangesWithEditor: c
    
