import = ['~/.config/alacritty/themes/one_half_light.toml']

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 1
y = 1
